name: Parse

on:
  schedule: 
    - cron: '00 12 */7 * *'
  workflow_dispatch:
    inputs:
      commitMessage:
        description: 'PostMessage commit'
        required: false
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r parser/requirements.txt
    - name: Run main
      run: python parser/main.py
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'instances/*'
        message: 'Update Instance lists${{ inputs.commitMessage }}'
        default_author: github_actions
        push: true
